<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class home_admin extends CI_Controller
{
    function __construct()
    {
        parent::__construct();
    }

    public function index()
    {
		if(!$this->session->userdata('loginedAdmin') || $this->session->userdata('loginedAdmin') != true)
		{
			redirect('Admin/Home_admin');
		}

		$this->load->view('templates/Admin/Home_admin');
    }    
    
}

/* End of file Workflows.php */
/* Location: ./application/controllers/Workflows.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2017-04-15 00:43:10 */
/* http://harviacode.com */